### PR TITLE
Update members.csv

### PR DESCRIPTION
**Pull request by jmduke**

### CODE REVIEW

**Comment by jmduke** [comment]
(JSON file going live rn)

**Comment by vladh** [comment]
Excited to have you! 🎉

**Comment by jmduke** [comment]
🫡 🫡 🫡

**Comment by vladh** [comment]
(Still 404ing for me, just FYI.)

**Comment by vladh** [comment]
Alright, the JSON file is live for me now!

@jmduke Could I ask for two small things?

1. Could you replace “OSS Pledge” with “Open Source Pledge” in the blog post?
2. Could you send us Buttondown's branding materials, preferably with different versions of the logo, so that we can put you on the Nasdaq tower in Times Square?

@chadwhitacre In between the [blog post](https://buttondown.com/blog/oss-pledge) and [Buttondown's Open Source page](https://buttondown.com/open-source), do you think any additions/changes are required?

**Review by vladh — CHANGES_REQUESTED** [review]
(See above comment.)

**Comment by vladh** [comment]
@jmduke Could we get Buttondown's branding materials in time for the marketing campaign deadline, as well as that one small change? That would be amazing. 💪🏻  Can I help clear anything up?

**Comment by jmduke** [comment]
Nope! Sorry, [got busy](https://jmduke.com/posts/post/lucy/) 😅 . I'll get this for you ASAP tomorrow.

**Comment by vladh** [comment]
@jmduke Amazing!!! Congratulations! 🎉 

No worries, we'll still get you on the big screen in time. :)

**Comment by jmduke** [comment]
icon

(And will get the wordmark shortly.)

**Comment by vladh** [comment]
@chadwhitacre Considering the [blog post](https://buttondown.com/blog/oss-pledge) and [Buttondown's Open Source page](https://buttondown.com/open-source), do you think we're okay to merge this for now?

**Comment by chadwhitacre** [comment]
I'd prefer to see something more transparent in terms of payments per year. The general intention is that members publish a blog post once a year that details this. As it stands with  buttondown.com/open-source it's hard to tell who got what in what year. It would be better to see the specific payments broken out by year vs. "since 20xx," but that could leave the annual report posts somewhat thin.

**Comment by vladh** [comment]
Thanks @chadwhitacre 🎉

**Comment by jmduke** [comment]
Just to address:

> I'd prefer to see something more transparent in terms of payments per year. The general intention is that members publish a blog post once a year that details this. As it stands with buttondown.com/open-source it's hard to tell who got what in what year. It would be better to see the specific payments broken out by year vs. "since 20xx," but that could leave the annual report posts somewhat thin.

We can have a standard year-end post that outlines the exact numbers, if that works?

**Comment by chadwhitacre** [comment]
That would be perfect, thanks @jmduke!

**Pull request merged**
