### PR TITLE
Press: new page

### LINKED ISSUE #202: List press coverage somewhere
I noticed [this Technical.ly story](https://technical.ly/software-development/open-source-pledge-developer-pay/ "How open-source software devs got corporations to pledge $1.3M for their tools") coming up in my news feeds and thought about how it'd be a good idea to have a press coverage list so people can read articles written about the project.

It could probably start as just an entry on the About page and maybe graduate to its own page after it hits some arbitrary size.

### PR DESCRIPTION
**Pull request by vladh**
Closes #202.

### CODE REVIEW

**Comment by chadwhitacre** [comment]
Seems to me the design should be more parallel between endorsements and press.

I.e., use the big quotation mark, don't link the quote itself, for press we could use the date where the URL/handle is on endorsements. Wdyt?

# Endorsements

image

# Press (on this PR)

image

**Comment by chadwhitacre** [comment]
We should also add a link in the footer.

**Comment by chadwhitacre** [comment]
And on the homepage let's reorder the sections from endorsements / members / press to members / endorsements / press.

**Comment by vladh** [comment]
> I.e., use the big quotation mark, don't link the quote itself, for press we could use the date where the URL/handle is on endorsements. Wdyt?

Happy to do this, but I guess the main question is — do we want to quote excerpts of the press articles?

**Comment by chadwhitacre** [comment]
oic ... hrm ... 🤔

**Comment by chadwhitacre** [comment]
I would say either pull excerpts or use the titles, since we were quoting the titles anyway.

If we use excerpts then I guess we can use the title as the link text.

**Comment by vladh** [comment]
Should be all good now!

**Review by Ethan-Arrowood — APPROVED** [review]

**Comment by vladh** [comment]
Thanks @Ethan-Arrowood, I think this is okay to merge for now — happy to fix any feedback if it arises, @chadwhitacre!

**Comment by selviano** [comment]
@vladh should we add new coverage here? Or create a new issue/repo for dropping links?

new article in TC https://techcrunch.com/2024/11/10/open-source-projects-draw-equity-free-funding-from-corporates-startups-and-even-vcs/

**Comment by vladh** [comment]
@selviano Thanks! Tomorrow I’ll handle creating an issue to drop links in, and adding this to the website.

**Pull request merged**
