### PR TITLE
Add Laravel

### PR DESCRIPTION
**Pull request by christophrumpel**

### CODE REVIEW

**Review by chadwhitacre — APPROVED** [review]

**Comment by vladh** [comment]
Amazing, so nice to have you on board! 🎉 

I’m seeing some broken Unicode characters in the description, is that just me? Looks like em dashes.

**Comment by chadwhitacre** [comment]
Where are you seeing them break, @vladh? I believe they are em dashes, yes.

**Comment by chadwhitacre** [comment]
They look fine here. At this point I would say let's prioritize landing this and then follow up with cleanups. We're on the HN homepage and we want Laravel to be included in the marketing cycle today.

image

**Comment by vladh** [comment]
Must be on my end, let’s get it merged!

**Pull request merged**
