### PR TITLE
add HeroDevs to members list

### PR DESCRIPTION
**Pull request by ljharb**
Per https://github.com/opensourcepledge/opensourcepledge.com/issues/112#issuecomment-2379765103.

### CODE REVIEW

**Comment by vladh** [comment]
Thanks @ljharb! I assume this is a draft, since almost all of the [required information][join] is missing. Will keep an eye on this.

[join]: https://opensourcepledge.com/join/

**Comment by ljharb** [comment]
That's what I wanted more clarity on :-) it sounds like this PR needs to contain an initial report. I'll fill that out.

**Comment by ljharb** [comment]
hmm, does that mean we can't join until we have a blog post written?

**Comment by vladh** [comment]
> hmm, does that mean we can't join until we have a blog post written?

Yep! The blog post is the main requirement for joining.

**Comment by ljharb** [comment]
Hmm, usually a "pledge" is a promise to do something you have not yet done. It takes time to coordinate writing a blog post.

**Comment by vladh** [comment]
Finding the perfect word/name can be tricky, for sure! But I think what we're asking for is pretty clearly laid out on the “Join” page, regardless of the name.

I totally get that writing a post takes coordination. Keep in mind that it doesn't have to be long or complicated. And you can take after some of the really nice blog posts our members have written so far.

I've compiled this list for you — maybe it helps a little bit?

* https://antithesis.com/blog/oss_pledge/
* https://astral.sh/blog/astral-oss-fund
* https://blog.stackblitz.com/posts/stackblitz-joins-osspledge/
* https://keygen.sh/blog/keygen-joins-osspledge/
* https://blog.val.town/blog/oss/
* https://getrector.com/blog/rector-is-joining-open-source-pledge
* https://httptoolkit.com/blog/open-source-funding-pledge/
* https://frontendmasters.com/blog/how-were-supporting-open-source-maintainers/
* https://blog.sentry.io/we-just-gave-500-000-dollars-to-open-source-maintainers/
* https://blog.gitbutler.com/open-source-pledge-2024/
* https://www.emergetools.com/blog/posts/emerge-joining-open-source-pledge
* https://www.browserbase.com/blog/browserbase-pledge-to-open-source
* https://www.scalar.com/blog/oss-pledge-2024
* https://chief.app/about#osspledge
* https://blog.packagist.com/packagist-is-joining-the-open-source-pledge/

Let me know if anything else is unclear!

**Comment by ljharb** [comment]
Thanks, JSON data is updated!

**Review by vladh — CHANGES_REQUESTED** [review]
Amazing, thanks for this @ljharb! Excited to have you guys on board. 🎉 

Just a few things:

* I noticed you have the HeroDevs homepage in `urlLearnMore`, but this should be a page about your Open Source commitments — if you don't have such a page, could you change this page to link to the blog post?
* Do you think you could provide us with your branding materials as detailed on the [Join page][https://opensourcepledge.com/join/], unless I've missed them?
* Could you change “OSS Pledge” to “Open Source Pledge” in the blog post title?
* Could you remove the trailing newline in the CSV?

Thank you! :)

**Comment by ljharb** [comment]
- urlLearnMore is updated
 - For branding materials, I specified `urlSquareLogoWithBackground`, but also there's https://www.herodevs.com/media-kit
 - i asked the blog post title be changed
 - sure (altho all files should always have a trailing newline)

**Comment by vladh** [comment]
> * For branding materials, I specified `urlSquareLogoWithBackground`, but also there's https://www.herodevs.com/media-kit

Ah, I was referring to step 5 of the Join page, which specifies in some detail which materials we require. The ones in your Media Kit work great!

Everything else looks good to me, at this point I'll just wait for a second review from @chadwhitacre. 🎉

**Review by chadwhitacre — APPROVED** [review]

**Comment by chadwhitacre** [comment]
I would love to see more detail behind the GHS sponsorships but they don't make it easy, maybe you can update the post with info from @vladh's GHS tooling?

Not blocking though. Welcome aboard!

**Comment by chadwhitacre** [comment]
Oof ... profile is looking rough. Is ", Inc." a super-strong part of your branding? Would prefer to remove. Also logo file is unflattering, seems that just the logo w/o the wordmark would work better. Can we update?

image

**Comment by vladh** [comment]
@ljharb I hate to be a broken record here, but please follow the instructions from the schema and the “Join” page:

> `urlSquareLogoWithBackground`
> 400px to 800px, non-transparent background — try using your GitHub avatar!

**Comment by ljharb** [comment]
Oops, sorry about that. Will update shortly.

**Comment by ljharb** [comment]
Done. The only one I had available has a transparent background, but it looks good on white or black, and I can make or request a non-transparent one in 12 hours or so (heading to the airport shortly)

**Comment by chadwhitacre** [comment]
> (heading to the airport shortly)

Of course you are. :-P

Thanks for jumping on this! @vladh How do we bring the latest into the website?

**Comment by vladh** [comment]
Fixed by running `./bin/update-all-members` in [11f5ccf](https://github.com/opensourcepledge/opensourcepledge.com/commit/11f5ccf1ad2f61971cc426c058240e69169bdb9a).

Thanks for all your work on this @ljharb!

**Pull request merged**
