### PR TITLE
Add license for resources

### LINKED ISSUE #223: Determine license for creative assets
We want to contribute assets to the Open Source Pledge and have those be usable in a variety of purposes, very similar to trademark purposes. Normally we'd just donate things under an open source license, but with media its actually more tricky than that. One example of what we want to avoid is someone taking the assets, uploading them to stockphoto, and trying to sell them. We also want to avoid people taking the assets and using them to represent something that is _not_ the pledge. I'm not familiar w/ media licensing so don't have any particular idea here, but it might be we just retain full IP and give a list of allowed purposes, in which we will implicitly grant a license.

### PR DESCRIPTION
**Pull request by vladh**
Closes #223.

### CODE REVIEW

**Comment by chadwhitacre** [comment]
Do you come up with this verbiage, @vladh?

**Comment by vladh** [comment]
@chadwhitacre Yes. Of course, I used some pages for inspiration on conditions and scenarios for banned usage, like https://go.dev/brand

**Comment by Ethan-Arrowood** [comment]
I'm sure this will need a lawyer's review

**Comment by chadwhitacre** [comment]
I can ask someone at Sentry to look it over.

**Comment by chadwhitacre** [comment]
[Moved to a Google Doc for review](https://docs.google.com/document/d/1dymhk3MUqbYjvHNk18jMrBXyhyLwODeHhaSj9kl9fXM/edit?usp=sharing). @gavin-zee Can you help us here?

**Comment by chadwhitacre** [comment]
@vladh We have a few comments in the Google doc if you want to bring those back here. 🙏

**Comment by vladh** [comment]
On it!

**Pull request merged**
