### PR TITLE
Add member logo board

### PR DESCRIPTION
**Pull request by vladh**
This addresses part of #126.

We had 21 logos, which divided into columns awkwardly, so one logo had to go. Sorry, Rector. :c

I think the one with 3 rows looks nice.

# Screenshots

## Actual mobile screenshot from my phone

IMG_7134

## All 5 rows

Screen Shot 2024-10-08 at 00 07 40

Screen Shot 2024-10-08 at 00 07 49

Screen Shot 2024-10-08 at 00 07 53

Screen Shot 2024-10-08 at 00 07 59

### 3 rows

Screen Shot 2024-10-08 at 00 08 11

Screen Shot 2024-10-08 at 00 08 15

Screen Shot 2024-10-08 at 00 08 18

Screen Shot 2024-10-08 at 00 08 21

## 2 rows

Screen Shot 2024-10-08 at 00 08 26

Screen Shot 2024-10-08 at 00 08 29

Screen Shot 2024-10-08 at 00 08 32

Screen Shot 2024-10-08 at 00 08 38

## 1 row

Screen Shot 2024-10-08 at 00 08 43

Screen Shot 2024-10-08 at 00 08 47

Screen Shot 2024-10-08 at 00 08 50

Screen Shot 2024-10-08 at 00 08 53

### CODE REVIEW

**Comment by vladh** [comment]
@chadwhitacre This is ready for review.

**Comment by vladh** [comment]
Changed to embed SVGs. Seems like a better idea.

**Comment by chadwhitacre** [comment]
Looking good!

> We had 21 logos, which divided into columns awkwardly, so one logo had to go.

What do you think of using the same algorithm we have now to show a selection of logos rather than all of them? That way we can give more companies exposure on the homepage as the effort grows.

**Comment by vladh** [comment]
Yep, on it! Shall we merge this for now so things look nicer for the launch?

**Comment by chadwhitacre** [comment]
Sure. :-)

**Pull request merged**
