### PR TITLE
Added promo kit content as mentioned in #196

### PR DESCRIPTION
**Pull request by 0xvish**
#196 
- [x] Added promo kit along side existing content on /resources page.
- [x] Update the links in the existing content.
- [ ] Review and update according to new mockups.

### CODE REVIEW

**Comment by vladh** [comment]
Thanks @0xvish! Is this ready for review?

**Comment by 0xvish** [comment]
@vladh LGTM, haven't added the href attributes yet, kindly do that as needed.

Otherwise, let me know if any changes are needed after review.

**Comment by vladh** [comment]
@0xvish Gotcha! Do you think you could update the links to refer to the corresponding places in our [Partner Kit][kit]? Let me know if there's confusing in there.

[kit]: https://drive.google.com/drive/folders/1W5-Jc4pjcCa1mk9UuyKlauwvuUeuwxxU

**Comment by vladh** [comment]
Thanks for your help @0xvish! 🙏🏻 

I made a few changes:

* 84125d4 — I noticed there were some unclosed tags, in particular `<section>` and `<main>`
* 9d78355 — I noticed some `.highlight-box` CSS that would never have an effect
* 32e25dd — Some headings had the wrong level
* f988af5 — I made some small tweaks to the spacing and text. Particularly, I removed the [pitch deck][deck] link, since it seems to be private, I don't have access to it either

I think this is good to merge now — we can make further adjustments as we go along. In particular, I'd like to add our [arguments board][arguments] when it's more fleshed out.

Thanks again! Feel free to [log your hours][finances].

---

@chadwhitacre Do you think we could make the [pitch deck][deck] link publicly accessible?

[deck]: https://drive.google.com/file/d/1vuK99jgptf2_tL5-ndhCrhzkdA-ymVbA/view?usp=share_link
[arguments]: https://kinopio.club/arguments-nMca8dVCTI0pH4EZ2YXpY
[finances]: https://github.com/opensourcepledge/finances

**Comment by 0xvish** [comment]
@vladh thanks for the fixes—looks great! 🙌 This was a minor task, so I won’t be claiming hours—happy to contribute in the open-source spirit. I’ll make sure to add my hourly rates to `teams.csv` for future reference.

**Comment by 0xvish** [comment]
I’d be happy to help with any tasks in the future—feel free to assign me ones you think I can handle!

**Comment by chadwhitacre** [comment]
> Do you think we could make the [pitch deck](https://drive.google.com/file/d/1vuK99jgptf2_tL5-ndhCrhzkdA-ymVbA/view?usp=share_link) link publicly accessible?

How about downloading it and adding it to this repo?

**Comment by chadwhitacre** [comment]
Thanks for the contribution @0xvish! :)

**Comment by vladh** [comment]
> How about downloading it and adding it to this repo?

Can do, but I can't access it myself. Requested access!

**Comment by chadwhitacre** [comment]
Nope, I'm confused. :)

**Pull request merged**
