### PR TITLE
Add platformatic to members.csv

### PR DESCRIPTION
**Pull request by alexandrabmanos**

### CODE REVIEW

**Review by vladh — CHANGES_REQUESTED** [review]
Hey, great to have you! 🎉 

I noticed a couple of things:

* Your [blog post](https://blog.platformatic.dev/platformatic-joins-the-open-source-pledge) 404s for me
* I'd recommend against using a Gist URL. Remember that you'll have to update this JSON file yearly, and you can't edit a Gist without changing its URL (as far as I know)
* `urlSquareLogoWithBackground` will be directly embedded in our website, so it should be an actual image file, not a Google Drive page
* Your name has a trailing space: `"name": "Platformatic ",`

**Comment by alexandrabmanos** [comment]
Hi @vladh,

We hadn't published the blog yet- it's now up the the link should be working/

We've solved the other issues now too. 

Let me know if that's working.

Thanks

**Comment by alexandrabmanos** [comment]
Hi Vlad- we hadn't published the blog yet- it's now up the the link should
be working/

We've solved the other issues now too.

Let me know if that's working.

Thanks,
Alex

**Review by vladh — DISMISSED** [review]
Thank you @alexandrabmanos, I love the blog post! :)

One more thing — here are the requirements for the logo image, from our [Join page](https://opensourcepledge.com/join/):

> Square, 400px to 800px, non-transparent background — try using your GitHub avatar!

Do you think you could change your logo to be in this format? Perhaps a square with a coloured background and your logomark in the middle would do it.

The reasoning here is that we want your logo to look its best on our website, instead of having a different aspect ratio to everything else.

**Comment by vladh** [comment]
It does! Just aesthetically, I would recommend only having the mark without the text, because your company name will already be shown next to your logo.

**Comment by vladh** [comment]
Maybe just linking to your GitHub avatar would be easiest?

**Comment by alexandrabmanos** [comment]
@vladh makes sense! Here's the text-free version
Platformatic logo (1)

**Comment by vladh** [comment]
Thank you! If you add that to the JSON file, we should be good! 🎉 Will just wait for a second review

**Comment by alexandrabmanos** [comment]
done!

**Comment by chadwhitacre** [comment]
Welcome aboard! 🎉

**Comment by alexandrabmanos** [comment]
Thank you!

**Comment by vladh** [comment]
Hey @alexandrabmanos! We're trying to make sure we have member branding materials to use for future marketing campaigns. Do you think you could send us vector versions of your logo? Ideally this would be multiple SVG files with different versions of your logo.

In case it helps, here's this example from VoidZero: https://voidzero.dev/branding

Thank you! :)

**Comment by alexandrabmanos** [comment]
Hi Vlad- apologies for missing this! Please find attached the vector
versions of our logo.

Thanks,
Alex

**Comment by vladh** [comment]
Thank you @alexandrabmanos! I don't think I can see an attachment, though. 🤔

**Comment by alexandrabmanos** [comment]
Platformatic-light-logo
Platformatic-dark-logo

Let me know if that shows now :)

**Comment by vladh** [comment]
Amazing, thank you! :)

**Pull request merged**
