### PR TITLE
Add Speakeasy to members.csv

### PR DESCRIPTION
**Pull request by ndimares**
Blog post written, json created!

### CODE REVIEW

**Review by vladh — DISMISSED** [review]
Amazing, thank you so much for joining! 🎉 🎉 🎉 

Just one tiny request: could you replace “OSS Pledge” with “Open Source Pledge” in the blog post?

I'll wait for a second review before merging.

**Comment by ndimares** [comment]
@vladh making that change now. Should be merged shortly.

**Comment by vladh** [comment]
Oops, I just realised it says says “OSS Pledge” in the hero image and the URL of the post. Could I ask you to change that as well? Just trying to avoid mix-ups about the name…

**Comment by ndimares** [comment]
> Oops, I just realised it says “OSS Pledge” in the hero image and the URL of the post. Could I ask you to change that as well? Just trying to avoid mix-ups about the name…

@vladh  No worries, just merging in the change with those edits now :)

**Comment by vladh** [comment]
@ndimares Tiny typo in the description:

> Since the first days of the company, we've always supported the OSS projects that are platform is built on.

→

> that our platform is built on

**Pull request merged**
