### PR TITLE
Add Tideways to pledge members

### PR DESCRIPTION
**Pull request by beberlei**
Hey! We would be happy to be a part of the open source pledge:

Our post for 2023: https://tideways.com/profiler/blog/tideways-joins-the-open-source-pledge

### CODE REVIEW

**Review by vladh — CHANGES_REQUESTED** [review]
Thank you for this, it's great to have you on board! 🎈 

I noticed a typo or two in your description — could I suggest this one?

> Tideways is a PHP Profiling, Monitoring and Exception Tracking tool. It's built on top of several Open Source libraries and frameworks in multiple languages.

Also, do you think you could replace instances of “Open-Source Pledge” with “Open Source Pledge” in the blog post?

Lastly, it would be great if we could have your branding materials!

> We need at least:
> 
>     * a glyph/icon in a square area, and
>     * a full name/wordmark in a wide rectangle,
> 
> or your nearest equivalents. For both versions, you should either include a high-resolution (> 800px wide) raster file with a transparent background (e.g. PNG), or preferably a vector file (e.g. SVG).
> 
> Expect the logos to be on a dark background, so include a light version for your logo, or expect us to make it all white.
> 
> For those pledging before October 8, you'll still have a chance to be included in our major outdoor advertising campaign, subject to available space and depending on how many pledges we get.

Other than that, everything looks good to me! I'll just wait for a second review.

**Comment by chadwhitacre** [comment]
> For those pledging before October 8, you'll still have a chance to be included in our major outdoor advertising campaign, subject to available space and depending on how many pledges we get.

Sadly the deadline for this was yesterday. Sorry. :(

**Comment by beberlei** [comment]
@chadwhitacre no worries

**Comment by chadwhitacre** [comment]
Otherwise everything looks in order, welcome aboard! 🙌

**Pull request merged**
