### PR TITLE
Stub out a resources page w/ stickers

### PR DESCRIPTION
**Pull request by chadwhitacre**
For #210 and #196.

### CODE REVIEW

**Review by vladh — CHANGES_REQUESTED** [review]
Wrong copyright headers. 😛 

Excited for the stickers!

**Comment by chadwhitacre** [comment]
Better in 23e3243818a202f57931e60b72d3eff81c8a6a52?

**Comment by chadwhitacre** [comment]
What license for the images, I wonder? 🤔

**Comment by vladh** [comment]
You can add them to the Functional Software section here!

https://github.com/opensourcepledge/opensourcepledge.com/blob/ae08640118db4fb601a5adc57437733cad86a898/REUSE.toml#L26

**Comment by vladh** [comment]
> Better in [23e3243](https://github.com/opensourcepledge/opensourcepledge.com/commit/23e3243818a202f57931e60b72d3eff81c8a6a52)?

If your contract requires copyright assignment yeah, otherwise it would just be (c) Chad Whitacre.

**Comment by chadwhitacre** [comment]
> requires copyright assignment

That's the norm with work-for-hire in the States. 👍

**Comment by chadwhitacre** [comment]
> You can add them to the Functional Software section here!

Okay but is "restricted" the right license for stickers we want people to be able to print? Seems like CC0 would be better? Even CC-BY seems too restrictive, though maybe the attribution is built-in since the sticker has the name?

**Comment by vladh** [comment]
Oh, right, sorry.

There is no up-to-date CC-SA [^1], and for CC-BY, a URL is not enough for attribution [^2]. But we can use CC-BY-SA and waive the attribution requirement [^3].

It looks to me like “Open Source Pledge” is not a registered trademark, at least from the USPTO search — perhaps registering it would be a good idea?

[^1]: https://opendata.stackexchange.com/a/9870
[^2]: https://creativecommons.org/faq/#attribution
[^3]: https://creativecommons.org/faq/#can-i-waive-license-terms-or-conditions

**Comment by chadwhitacre** [comment]
Went with d08387f48f6884d23a409dbb07e0dc515923c75c based on https://github.com/opensourcepledge/opensourcepledge.com/issues/210#issuecomment-2420846331. 👍

**Pull request merged**
