### PR TITLE
Add blog

### LINKED ISSUE #228: Consider starting a blog
It looks like we need some kind of blog to address longer-form topics, such as the question in #227. There have been questions from the community that require this kind of treatment.

I'm happy to get one started. We can already pre-populate it with eg some things from Open Path, if @chadwhitacre agrees.

Any objections?

### PR DESCRIPTION
**Pull request by vladh**
Closes #228

Screen Shot 2024-10-31 at 20 01 09

Screen Shot 2024-10-31 at 20 01 13

Screen Shot 2024-10-31 at 20 01 18

Screen Shot 2024-10-31 at 20 01 22

### CODE REVIEW

**Comment by selviano** [comment]
hey @vladh this looks great. Is this a mockup or is this ready to ship? Curious what CMS you used to make it? We are going to onboard Sanity soon so it would be cool to use their headless CMS if it makes sense

**Comment by vladh** [comment]
Hey @selviano! This is ready to ship. I used some Astro features to set up a system where we can easily author Markdown articles (same flavour of Markdown as these GitHub comments etc).

Here's an example of what that looks like: https://github.com/opensourcepledge/opensourcepledge.com/blob/vladh/create-blog/src/content/articles/join-the-pledge.md?plain=1

From my perspective, this meets our current needs, but if you'd like to have Sanity implemented, I can absolutely do that.

**Comment by selviano** [comment]
@vladh I think at some point we will want a full-fledged CMS, but I don't know that we need it now. WRT Sanity, I know lots of people who love it, but that doesn't necessarily mean it's the best for our use case. So I'll defer to you on that. I just think that all things being equal, we should use Pledge members' tech wherever we can.

**Comment by vladh** [comment]
> @vladh I think at some point we will want a full-fledged CMS, but I don't know that we need it now. WRT Sanity, I know lots of people who love it, but that doesn't necessarily mean it's the best for our use case. So I'll defer to you on that. I just think that all things being equal, we should use Pledge members' tech wherever we can.

Gotcha! We can use the Astro solution for now, then switch to Sanity when required.

**Comment by vladh** [comment]
> @vladh Worth standardizing w/ the quote and date format from the press page?

Good point, on it!

**Comment by vladh** [comment]
@chadwhitacre Done!

**Comment by chadwhitacre** [comment]
Can we be consistent with nomenclature? Looking at blog vs. articles in URL and h1, I think blog is the more standard in our case.

image

**Comment by chadwhitacre** [comment]
Ooh! I like the usage in blockquotes. I was thinking of the listing page, though. Shouldn't press and blog have consistent design?

**Comment by vladh** [comment]
> Can we be consistent with nomenclature? Looking at blog vs. articles in URL and h1, I think blog is the more standard in our case.

Done!

> Ooh! I like the usage in blockquotes. I was thinking of the listing page, though. Shouldn't press and blog have consistent design?

Right, of course. Done!

**Pull request merged**
